#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/Pictures/wallpapers/planets.png
"{$HOME}/.cache/wal/colors.sh"
polybar topbar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color       "$color1"
bspc config active_border_color       "$color2"
bspc config focused_border_color      "$color15"

bspc config presel_feeback_color      "$color1"

bspc config focus_follows_pointer     true 

bspc config border_width          2
bspc config window_gap            25

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
