# Shell variables
# Generated by 'wal'
wallpaper='/home/dulinniel/Pictures/wallpapers/planets.png'

# Special
background='#0f0f0e'
foreground='#c5c5c3'
cursor='#c5c5c3'

# Colors
color0='#0f0f0e'
color1='#5EA16C'
color2='#FDA52E'
color3='#C6B862'
color4='#576797'
color5='#A36B9F'
color6='#58A4AB'
color7='#c5c5c3'
color8='#898988'
color9='#5EA16C'
color10='#FDA52E'
color11='#C6B862'
color12='#576797'
color13='#A36B9F'
color14='#58A4AB'
color15='#c5c5c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
