--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dulinniel/Pictures/wallpapers/planets.png"

-- Special
background="#0f0f0e"
foreground="#c5c5c3"
cursor="#c5c5c3"

-- Colors
color0="#0f0f0e"
color1="#5EA16C"
color2="#FDA52E"
color3="#C6B862"
color4="#576797"
color5="#A36B9F"
color6="#58A4AB"
color7="#c5c5c3"
color8="#898988"
color9="#5EA16C"
color10="#FDA52E"
color11="#C6B862"
color12="#576797"
color13="#A36B9F"
color14="#58A4AB"
color15="#c5c5c3"
